/**
 * Master Schedule Data Structure
 * Contains full 24-hour schedule data for Monday through Sunday.
 * Updated Sunday: 7 Hours Sleep, 1 Hour Power Nap, Dedicated Play Time / Recreation, No Selenium/BCA studies.
 */

const SCHEDULE_DATA = {
  monday: [
    { id: "mon-1", start: "00:00", end: "05:00", title: "Sleep", category: "sleep", icon: "💤", desc: "Rest and recovery" },
    { id: "mon-2", start: "05:00", end: "05:15", title: "Wake Up & Hydrate", category: "routine", icon: "🌅", desc: "Hydration & mental preparation" },
    { id: "mon-3", start: "05:15", end: "06:45", title: "Exercise Session", category: "exercise", icon: "🏋️", desc: "100 Pushups & 50 Chin-ups" },
    { id: "mon-4", start: "06:45", end: "07:15", title: "Bathing & Hygiene", category: "routine", icon: "🧼", desc: "Alternate day bathing" },
    { id: "mon-5", start: "07:15", end: "08:15", title: "Book Reading", category: "reading", icon: "📚", desc: "Daily reading habit" },
    { id: "mon-6", start: "08:15", end: "08:30", title: "Quick Breakfast", category: "break", icon: "☕", desc: "Breakfast & college prep" },
    { id: "mon-7", start: "08:30", end: "09:00", title: "Travel to College", category: "travel", icon: "🚶", desc: "Commute to Kristu Jayanti" },
    { id: "mon-8", start: "09:00", end: "12:50", title: "College Classes", category: "college", icon: "🎓", desc: "Cloud, Python, RM, Library" },
    { id: "mon-9", start: "12:50", end: "13:20", title: "Travel Home", category: "travel", icon: "🚶", desc: "Commute back home" },
    { id: "mon-10", start: "13:20", end: "14:20", title: "Afternoon Power Nap", category: "sleep", icon: "😴", desc: "1 Hour Post-College Nap & Rest" },
    { id: "mon-11", start: "14:20", end: "14:40", title: "Lunch & Refresh", category: "break", icon: "🍱", desc: "Lunch & transition break" },
    { id: "mon-12", start: "14:40", end: "16:40", title: "Selenium Java Automation", category: "study", icon: "⚡", desc: "Automation testing learning" },
    { id: "mon-13", start: "16:40", end: "18:00", title: "BCA Study: Python Theory", category: "study", icon: "📖", desc: "Core Python concepts & syntax" },
    { id: "mon-14", start: "18:00", end: "23:00", title: "Rapido Work Shift", category: "rapido", icon: "🛵", desc: "Evening shift (Target ₹620 min)" },
    { id: "mon-15", start: "23:00", end: "23:40", title: "BCA Study: Python Revision", category: "study", icon: "📖", desc: "Evening study recap" },
    { id: "mon-16", start: "23:40", end: "23:59", title: "Dinner & Sleep Prep", category: "routine", icon: "🌌", desc: "Wind down for sleep" }
  ],
  tuesday: [
    { id: "tue-1", start: "00:00", end: "05:00", title: "Sleep", category: "sleep", icon: "💤", desc: "Rest and recovery" },
    { id: "tue-2", start: "05:00", end: "05:15", title: "Wake Up & Hydrate", category: "routine", icon: "🌅", desc: "Morning hydration" },
    { id: "tue-3", start: "05:15", end: "06:00", title: "Book Reading", category: "reading", icon: "📚", desc: "Reading habit session" },
    { id: "tue-4", start: "06:00", end: "08:00", title: "Rapido Morning Shift", category: "rapido", icon: "🛵", desc: "Peak morning surge (2 hrs)" },
    { id: "tue-5", start: "08:00", end: "09:30", title: "Exercise Session", category: "exercise", icon: "🏋️", desc: "1.5 Hours physical training" },
    { id: "tue-6", start: "09:30", end: "10:15", title: "Freshen Up & Breakfast", category: "break", icon: "🍱", desc: "Freshen up & Breakfast" },
    { id: "tue-7", start: "10:15", end: "10:30", title: "College Prep", category: "break", icon: "☕", desc: "Transition & prep" },
    { id: "tue-8", start: "10:30", end: "11:00", title: "Travel to College", category: "travel", icon: "🚶", desc: "Commute to college" },
    { id: "tue-9", start: "11:00", end: "16:30", title: "College Classes & Lab", category: "college", icon: "🎓", desc: "DWM Lab, Python, DMW, RM" },
    { id: "tue-10", start: "16:30", end: "17:00", title: "Travel Home", category: "travel", icon: "🚶", desc: "Commute back home" },
    { id: "tue-11", start: "17:00", end: "18:00", title: "Afternoon Power Nap", category: "sleep", icon: "😴", desc: "1 Hour Post-College Nap & Rest" },
    { id: "tue-12", start: "18:00", end: "21:00", title: "Rapido Evening Shift", category: "rapido", icon: "🛵", desc: "Peak evening surge (3 hrs - Total 5h)" },
    { id: "tue-13", start: "21:00", end: "23:00", title: "Selenium Java Automation", category: "study", icon: "⚡", desc: "Automation testing learning" },
    { id: "tue-14", start: "23:00", end: "23:59", title: "BCA Study: Python Practicals", category: "study", icon: "📖", desc: "Python coding lab exercises" }
  ],
  wednesday: [
    { id: "wed-1", start: "00:00", end: "05:00", title: "Sleep", category: "sleep", icon: "💤", desc: "Rest and recovery" },
    { id: "wed-2", start: "05:00", end: "05:15", title: "Wake Up & Hydrate", category: "routine", icon: "🌅", desc: "Hydration & mental preparation" },
    { id: "wed-3", start: "05:15", end: "06:45", title: "Exercise Session", category: "exercise", icon: "🏋️", desc: "1.5 Hours physical training" },
    { id: "wed-4", start: "06:45", end: "07:15", title: "Bathing & Hygiene", category: "routine", icon: "🧼", desc: "Alternate day bathing" },
    { id: "wed-5", start: "07:15", end: "08:15", title: "Book Reading", category: "reading", icon: "📚", desc: "Daily reading habit" },
    { id: "wed-6", start: "08:15", end: "08:30", title: "Quick Breakfast", category: "break", icon: "☕", desc: "Breakfast & college prep" },
    { id: "wed-7", start: "08:30", end: "09:00", title: "Travel to College", category: "travel", icon: "🚶", desc: "Commute to Kristu Jayanti" },
    { id: "wed-8", start: "09:00", end: "12:50", title: "College Classes", category: "college", icon: "🎓", desc: "Cloud, DMW, Python Lab" },
    { id: "wed-9", start: "12:50", end: "13:20", title: "Travel Home", category: "travel", icon: "🚶", desc: "Commute back home" },
    { id: "wed-10", start: "13:20", end: "14:20", title: "Afternoon Power Nap", category: "sleep", icon: "😴", desc: "1 Hour Post-College Nap & Rest" },
    { id: "wed-11", start: "14:20", end: "14:40", title: "Lunch & Refresh", category: "break", icon: "🍱", desc: "Lunch and short rest" },
    { id: "wed-12", start: "14:40", end: "16:40", title: "Selenium Java Automation", category: "study", icon: "⚡", desc: "Automation testing learning" },
    { id: "wed-13", start: "16:40", end: "18:00", title: "BCA Study: DMW Theory", category: "study", icon: "📖", desc: "Data Mining & Warehousing" },
    { id: "wed-14", start: "18:00", end: "23:00", title: "Rapido Work Shift", category: "rapido", icon: "🛵", desc: "Evening shift (Target ₹620 min)" },
    { id: "wed-15", start: "23:00", end: "23:40", title: "BCA Study: DMW Revision", category: "study", icon: "📖", desc: "Evening study recap" },
    { id: "wed-16", start: "23:40", end: "23:59", title: "Dinner & Sleep Prep", category: "routine", icon: "🌌", desc: "Wind down for sleep" }
  ],
  thursday: [
    { id: "thu-1", start: "00:00", end: "05:00", title: "Sleep", category: "sleep", icon: "💤", desc: "Rest and recovery" },
    { id: "thu-2", start: "05:00", end: "05:15", title: "Wake Up & Hydrate", category: "routine", icon: "🌅", desc: "Morning hydration" },
    { id: "thu-3", start: "05:15", end: "06:00", title: "Book Reading", category: "reading", icon: "📚", desc: "Reading habit session" },
    { id: "thu-4", start: "06:00", end: "08:00", title: "Rapido Morning Shift", category: "rapido", icon: "🛵", desc: "Peak morning surge (2 hrs)" },
    { id: "thu-5", start: "08:00", end: "09:30", title: "Exercise Session", category: "exercise", icon: "🏋️", desc: "1.5 Hours physical training" },
    { id: "thu-6", start: "09:30", end: "11:15", title: "Selenium Java (Part 1)", category: "study", icon: "⚡", desc: "Automation testing study" },
    { id: "thu-7", start: "11:15", end: "11:30", title: "Early Lunch & Prep", category: "break", icon: "🍱", desc: "Lunch before college" },
    { id: "thu-8", start: "11:30", end: "12:00", title: "Travel to College", category: "travel", icon: "🚶", desc: "Commute to college" },
    { id: "thu-9", start: "12:00", end: "15:30", title: "College Classes", category: "college", icon: "🎓", desc: "Mentoring, Python, DMW" },
    { id: "thu-10", start: "15:30", end: "16:00", title: "Travel Home", category: "travel", icon: "🚶", desc: "Commute back home" },
    { id: "thu-11", start: "16:00", end: "17:00", title: "Afternoon Power Nap", category: "sleep", icon: "😴", desc: "1 Hour Post-College Nap & Rest" },
    { id: "thu-12", start: "17:00", end: "20:00", title: "Rapido Evening Shift", category: "rapido", icon: "🛵", desc: "Peak evening surge (3 hrs - Total 5h)" },
    { id: "thu-13", start: "20:00", end: "22:00", title: "BCA Study: DMW Practicals", category: "study", icon: "📖", desc: "DMW SQL / Lab exercises" },
    { id: "thu-14", start: "22:00", end: "22:15", title: "Selenium Java (Part 2)", category: "study", icon: "⚡", desc: "Automation testing recap" },
    { id: "thu-15", start: "22:15", end: "23:59", title: "Dinner & Sleep Prep", category: "routine", icon: "🌌", desc: "Wind down for sleep" }
  ],
  friday: [
    { id: "fri-1", start: "00:00", end: "05:00", title: "Sleep", category: "sleep", icon: "💤", desc: "Rest and recovery" },
    { id: "fri-2", start: "05:00", end: "05:15", title: "Wake Up & Hydrate", category: "routine", icon: "🌅", desc: "Hydration & mental preparation" },
    { id: "fri-3", start: "05:15", end: "06:45", title: "Exercise Session", category: "exercise", icon: "🏋️", desc: "1.5 Hours physical training" },
    { id: "fri-4", start: "06:45", end: "07:15", title: "Bathing & Hygiene", category: "routine", icon: "🧼", desc: "Alternate day bathing" },
    { id: "fri-5", start: "07:15", end: "08:15", title: "Book Reading", category: "reading", icon: "📚", desc: "Daily reading habit" },
    { id: "fri-6", start: "08:15", end: "08:30", title: "Quick Breakfast", category: "break", icon: "☕", desc: "Breakfast & college prep" },
    { id: "fri-7", start: "08:30", end: "09:00", title: "Travel to College", category: "travel", icon: "🚶", desc: "Commute to Kristu Jayanti" },
    { id: "fri-8", start: "09:00", end: "12:50", title: "College Classes", category: "college", icon: "🎓", desc: "RM, CA, CET, Cloud" },
    { id: "fri-9", start: "12:50", end: "13:20", title: "Travel Home", category: "travel", icon: "🚶", desc: "Commute back home" },
    { id: "fri-10", start: "13:20", end: "14:20", title: "Afternoon Power Nap", category: "sleep", icon: "😴", desc: "1 Hour Post-College Nap & Rest" },
    { id: "fri-11", start: "14:20", end: "14:40", title: "Lunch & Refresh", category: "break", icon: "🍱", desc: "Lunch and short rest" },
    { id: "fri-12", start: "14:40", end: "16:40", title: "Selenium Java Automation", category: "study", icon: "⚡", desc: "Automation testing learning" },
    { id: "fri-13", start: "16:40", end: "18:00", title: "BCA Study: Cloud Computing", category: "study", icon: "📖", desc: "Cloud concepts & Virtualization" },
    { id: "fri-14", start: "18:00", end: "23:00", title: "Rapido Work Shift", category: "rapido", icon: "🛵", desc: "Evening shift (Target ₹620 min)" },
    { id: "fri-15", start: "23:00", end: "23:40", title: "BCA Study: Cloud Revision", category: "study", icon: "📖", desc: "Evening study recap" },
    { id: "fri-16", start: "23:40", end: "23:59", title: "Dinner & Sleep Prep", category: "routine", icon: "🌌", desc: "Wind down for sleep" }
  ],
  saturday: [
    { id: "sat-1", start: "00:00", end: "07:00", title: "Sleep", category: "sleep", icon: "💤", desc: "Rest & Recovery (7 Hours)" },
    { id: "sat-2", start: "07:00", end: "07:15", title: "Wake Up & Hydrate", category: "routine", icon: "🌅", desc: "Morning hydration" },
    { id: "sat-3", start: "07:15", end: "08:45", title: "Exercise Session", category: "exercise", icon: "🏋️", desc: "1.5 Hours physical training" },
    { id: "sat-4", start: "08:45", end: "09:00", title: "Transition Break", category: "break", icon: "☕", desc: "Short rest" },
    { id: "sat-5", start: "09:00", end: "10:00", title: "Book Reading", category: "reading", icon: "📚", desc: "Daily reading habit" },
    { id: "sat-6", start: "10:00", end: "10:30", title: "Breakfast & College Prep", category: "break", icon: "🍱", desc: "Breakfast & college prep" },
    { id: "sat-7", start: "10:30", end: "11:00", title: "Travel to College", category: "travel", icon: "🚶", desc: "Commute to college" },
    { id: "sat-8", start: "11:00", end: "12:50", title: "PRISM: Selenium Java", category: "study", icon: "⚡", desc: "Self Development Class: Selenium Java Practice" },
    { id: "sat-9", start: "12:50", end: "13:20", title: "Travel Home", category: "travel", icon: "🚶", desc: "Commute back home" },
    { id: "sat-10", start: "13:20", end: "14:20", title: "Afternoon Power Nap", category: "sleep", icon: "😴", desc: "1 Hour Post-College Nap & Rest" },
    { id: "sat-11", start: "14:20", end: "14:40", title: "Lunch Break", category: "break", icon: "🍱", desc: "Lunch break" },
    { id: "sat-12", start: "14:40", end: "16:00", title: "BCA Study: Research Methods", category: "study", icon: "📖", desc: "Research Methodology (RM) Study" },
    { id: "sat-13", start: "16:00", end: "23:00", title: "Rapido Weekend Shift", category: "rapido", icon: "🛵", desc: "Weekend Peak (7 Hours - Target ₹1K–1.2K)" },
    { id: "sat-14", start: "23:00", end: "23:59", title: "Pencil Sketching Hobby", category: "hobby", icon: "🎨", desc: "Weekend Sketching Session (2 Hours)" }
  ],
  sunday: [
    { id: "sun-1", start: "00:00", end: "07:00", title: "Sleep", category: "sleep", icon: "💤", desc: "Rest & Recovery (7 Hours)" },
    { id: "sun-2", start: "07:00", end: "07:15", title: "Wake Up & Hydrate", category: "routine", icon: "🌅", desc: "Morning hydration" },
    { id: "sun-3", start: "07:15", end: "08:45", title: "Exercise Session", category: "exercise", icon: "🏋️", desc: "1.5 Hours physical training" },
    { id: "sun-4", start: "08:45", end: "09:15", title: "Bathing & Hygiene", category: "routine", icon: "🧼", desc: "Alternate day bathing" },
    { id: "sun-5", start: "09:15", end: "10:15", title: "Book Reading", category: "reading", icon: "📚", desc: "Daily reading habit" },
    { id: "sun-6", start: "10:15", end: "10:45", title: "Breakfast Break", category: "break", icon: "☕", desc: "Breakfast & relax" },
    { id: "sun-7", start: "10:45", end: "12:15", title: "Play Time & Recreation", category: "break", icon: "🎮", desc: "Dedicated sports, games & recreation time" },
    { id: "sun-8", start: "12:15", end: "13:15", title: "Afternoon Power Nap", category: "sleep", icon: "😴", desc: "1 Hour Afternoon Nap & Rest" },
    { id: "sun-9", start: "13:15", end: "20:15", title: "Rapido Weekend Shift", category: "rapido", icon: "🛵", desc: "Weekend Peak (7 Hours - Target ₹1K–1.2K)" },
    { id: "sun-10", start: "20:15", end: "20:45", title: "Dinner & Refresh", category: "break", icon: "🍱", desc: "Dinner break" },
    { id: "sun-11", start: "20:45", end: "22:45", title: "Pencil Sketching Hobby", category: "hobby", icon: "🎨", desc: "Weekend Sketching Session (2 Hours)" },
    { id: "sun-12", start: "22:45", end: "23:59", title: "Wind Down & Sleep Prep", category: "routine", icon: "🌌", desc: "Rest & night wind down" }
  ]
};
